### ISSUE TITLE
Add a text field (S)

### ISSUE THREAD

**Issue by ankonym** [Alster-Hamburgers/leap_web#1]
I should be able to fill in my token    

"On the sign up page, There should be a field for a token. 
It should have the same styling as the username and password fields."

**Comment by ankonym** [comment]
Done!

**Comment by kaeff** [comment]
Just fyi, we left the card in ready for sign-off to not forget that we still need to send a pull request. For that, the code needs to be pushed in the repo. @ankonym where you able to push your code successfully? where can we find it?

**Comment by ankonym** [comment]
@kaeff Hm, somehow I'm not able to commit all the files (srp resists mysteriously), so I didn't push it yet but hopefully will later today.
