### ISSUE TITLE
Use srp.js from upstream instead of our fork

### ISSUE THREAD

**Issue by kaeff** [Alster-Hamburgers/leap_web#24]
Since a93b112fc727785a559132aa7c9a782463e912e1 we're using a fork of srp.js to be able to send invite codes to the server during sign up. In order to be able to contribute our code back to the upstream repository (leapcode/leap_web), the git submodule must point back to the upstream srp.js repository (leapcode/srp_js). There are 2 ways of achieving that

1) Have our changes in srp.js merged upstream in a pull request
2) Move the parts of the code that are specific to the application (i.e. that leap_web uses invite codes) into the app's javascript code and out of srp.js (we added leap_web-specific code to srp.js in https://github.com/Alster-Hamburgers/srp_js/commit/26b6d11f1eeae2c0f1b47ce2230d5e15684d6483)

I'd vote for option 2). While 1) would work, now every app that uses the srp.js library is expected to work with invite codes. From a design standpoint, there is what we call a circular dependency: leap_web depends on srp.js (when the form is submitted, srp is used to send the data to the server), but now, srp.js also depends on leap_web (it reads the invite code from the page when sending data to the server). This defies the idea of separating the srp.js from the app.

**Comment by kaeff** [comment]
Proposed the necessary change in leapcode/srp_js in this PR: https://github.com/leapcode/srp_js/pull/6

**Comment by ankonym** [comment]
Merged in pull request #194 to leapcode/leap_web
