### ISSUE TITLE
#9 Clean up test setup 

### ISSUE THREAD

**Issue by ayajaff** [Alster-Hamburgers/leap_web#9]
Apparently it's a bit of a chaos and we need to talk to one of the LEAP-Team members for this one

**Comment by ankonym** [comment]
Also, our tests currently create a whole lot of invite codes (74) every time they run. We should delete them after testing instead so we don't unnecessarily fill up the database.

**Comment by ankonym** [comment]
Discussed this with Christoph - since the leap_web tests only run during development, this actually isn't a real issue. (Cleaning up the test setup after the leap_platform tests is a different user story, and more useful, so I'll close this one and keep the other.)
